import assert from 'node:assert/strict';
import { catalog,examples,parseCsv,weighted } from '../app/farmos/feed-data.ts';
const r=(share,price,protein)=>({id:String(share),name:'Test',share:String(share),price,protein});
assert.equal(weighted([r(30,'1000','10'),r(20,'2800','46'),r(50,'600','16')],'price'),1160);
assert.ok(Math.abs(weighted([r(30,'1000','9'),r(20,'2800','46'),r(50,'600','16')],'protein')-19.9)<1e-9);
assert.equal(weighted([r(50,'1000',''),r(50,'2000','40')],'protein'),null);
assert.equal(weighted([r(0,'',''),r(100,'2000','40')],'protein'),40);
assert.equal(weighted([r(100,'','40')],'price'),null);
assert.equal(parseCsv('name,price,protein\n"Meal, local",1200,45')[0].name,'Meal, local');
assert.equal(parseCsv('\uFEFFname,price,protein\r\nSoy,,\r\n')[0].protein,'');
assert.throws(()=>parseCsv('name,protein\nSoy,101'),/between 0 and 100/);
assert.throws(()=>parseCsv('name,price\nSoy,-2'),/non-negative/);
assert.throws(()=>parseCsv('name,price\nSoy,2,3'),/column count/);
assert.throws(()=>parseCsv('name,price\n"Soy,2'),/Unclosed/);
assert.throws(()=>parseCsv('name,name\nSoy,Soy'),/Duplicate/);
const template='name,category,price,protein,fat,fibre,ash,moisture,calcium,phosphorus,lysine,methionine\nMy ingredient,Custom,,,,,,,,,,\n';
assert.equal(parseCsv(template).length,1);
for(const ex of examples){assert.ok(Math.abs(ex.parts.reduce((s,[,v])=>s+v,0)-100)<1e-9);assert.ok(ex.parts.every(([i])=>catalog[i]));}
assert.equal(examples[2].parts[1][0],17);
assert.ok(catalog[17].name.startsWith('Poultry by-product'));
console.log('FarmOS: golden totals, missing values, zero inclusion, CSV validation and template totals passed.');
